pghistory/tests/test_tracking.py, pghistory/tracking.py, pyproject.toml
Invalid SQL was generated from context values with single quotes when
using ``pghistory.context``. Single quotes are now properly escaped, and
a failing test case was created to cover this scenario.
Type: bug
@tomage this addresses #2 
Although it is possible to pass in the context variable as a SQL var and then let mogrify handle this, I'm hesitant to populate the SQL variables of the hook since the fix is to simply escape the single quote. Single quotes in postgres are escaped with another single quote.
I wrote a failing test case for this scenario and verified the fix
=> Escape single quotes in tracked context

.circleci/config.yml, .env.template, .gitignore, .pre-commit-config.yaml, CONTRIBUTING.rst, LICENSE, Makefile, devops.py, docker-compose.yml, docs/_static/css/custom.css, docs/conf.py, manage.py, pghistory/core.py, pghistory/migrations/0001_initial.py, pghistory/models.py, pghistory/tests/models.py, pghistory/tests/test_core.py, pghistory/tests/test_middleware.py, pghistory/tests/test_models.py, pghistory/tests/urls.py, pghistory/tracking.py, pghistory/trigger.py, poetry.lock, pyproject.toml, settings.py, setup.cfg, temple.yaml, tox.ini
Type: trivial
This also adds docker-based development hooks and guidelines making it easier for contributors to test changes
=> Updated with latest template, dropping 3.6 support and adding Django 4 support

README.rst, pghistory/tests/models.py, pghistory/tests/test_core.py, pghistory/trigger.py
The BeforeDelete event was referencing the wrong trigger value (NEW).
Code was updated to reference the proper OLD row for this event,
and a failing test case was added.
Type: bug
=> Fixed bug in BeforeDelete event

README.rst, pghistory/middleware.py, pghistory/tests/test_middleware.py
Currently the middleware adds a context for POST, PUT, and PATCH requests. This leaves out DELETE requests as the only ones that can affect a model without a context. Updating middleware to add a context for DELETE requests along with POST, PUT and PATCH.
Type: feature
=> Add support for delete requests in pghistory middleware

README.rst, docs/extras.rst, pghistory/models.py, pghistory/tests/test_models.py
This expands the `target()` function to accept a queryset or a list of objects on top of the exisiting one object.
=> Allow target() to receive a queryset or list of objects.

pghistory/middleware.py, pghistory/tests/test_middleware.py
Currently the middleware adds a context for POST, PUT, PATCH and DELETE requests. Updating middleware to add a context for GET requests along with POST, PUT, PATCH and DELETE.
Type: feature
Additional details:
Here's a sample workflow where the context if of importance during GET requests.
- When a `GET` request goes via the auth workflow - a [successful login triggers the user_logged_in signal ](https://github.com/django/django/blob/main/django/contrib/auth/__init__.py#L144) of the user model. 
- This signal is used by django to [update the `last_login_time` attribute in the User model](https://github.com/django/django/blob/main/django%2Fcontrib%2Fauth%2Fmodels.py#L17-L23)
=> Add support for GET requests in pghistory middleware

README.rst, pghistory/__init__.py, poetry.lock
Fix this warning:
```
../../usr/local/lib/python3.10/site-packages/django/apps/registry.py:91
/usr/local/lib/python3.10/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'pghistory' defines default_app_config = 'pghistory.apps.PGHistoryConfig'. Django now detects this configuration automatically. You can remove default_app_config.
app_config = AppConfig.create(entry)
```
=> Fix default_app_config warning on Django 3.2+

README.rst, pghistory/middleware.py, pghistory/tests/test_middleware.py
When the project has overridden the `User` model, they might use some other field as the primary key.
In this case there is no `id` field and the code will fail with `AttributeError: 'User' object has no attribute 'id'`.
Using the `pk` field instead will solve the issue since it will automatically point to the real primary key field.
=> Use `pk` instead of `id` to get the user's primary key

pghistory/models.py, pghistory/tests/test_models.py
Django's ``dumpdata`` command is now compatible with pghistory's AggregateEvent model.
Type: bug
Addresses #21   #44
=> Fix issues related to the ``dumpdata`` command

pghistory/runtime.py, pghistory/tests/test_tracking.py
Previously data passed to `SET LOCAL` statements was directly added into the SQL. This could lead to SQL injection because pscyopg2's escaping would fail. The fix is to pass the data through `params` in order to get it escaped.
This problem arose a client project where a botted URL with an encoded HTTP newline, `%0d%0a`, was added to the context. Because those % symbols mean "insert parameter here" to psycopg2, the `execute()` call crashed with `IndexError: tuple index out of range`.
So %'s in context vars could cause a crash like that, perhaps a DoS vector. But I don't think it's exploitable to run arbitrary SQL, given the JSON string escaping.
=> Fix SQL injection vector

pghistory/runtime.py
Calls to SET LOCAL are not normalized, making pghistory very unfriendly to pg_stat_statements and monitoring tools relying on it.
Replacing it with calls to set_config is quite simple and will fix this issue.
fix #81
=> use set_config instead of SET LOCAL (#81)

pghistory/runtime.py
Remove the PyTypeChecker warning by using the proper parameter name (kwargs) in the context init function
Type: trivial
=> Remove the PyTypeChecker warning

Makefile, pghistory/core.py, pghistory/tests/test_core.py
Type: bug
Fix bug where `fields` being set to an empty list in `create_event_model` leads to all fields being included.
=> Fix Empty List being passed into `create_event_model`

pghistory/config.py, pghistory/trigger.py
Currently, the code uses `NOW()` PostgreSQL function to set the value for the `pgh_created_at` field.
`NOW()` returns the same timestamp within the transaction, i.e. it may insert multiple rows in a batch to one events table with the same `pgh_created_at` value.
Technically, it's preferable to use the `clock_timestamp()` function instead. This will make sure that the `pgh_created_at` values will always have a real timestamp.
As this is a breaking change, I suggest adding a configuration that would allow setting the default function used to populate `pgh_created_at` field.
=> Add possibility to change the function used to populate `pgh_created_at` field

pghistory/config.py, pghistory/tests/test_config.py
Using the `PGHISTORY_DEFAULT_TRACKERS` setting doesn't seem to actually work, as the provided `pghistory.Tracker` instances are re-used across multiple models.
It doesn't look like `pghistory.Tracker`s were designed to be re-used across multiple models, so for now I've opted to make `pghistory.config.default_trackers` copy them via `copy.deep_copy` to ensure we get new instances each time. This is of course based on the assumption that doing `copy.deep_copy(tracker)` is valid.
An alternative fix to this could be making `PGHISTORY_DEFAULT_TRACKERS` require a callable instead, so users could do:
```python
PGHISTORY_DEFAULT_TRACKERS = lambda: [InsertEvent(), UpdateEvent(), DeleteEvent()]
```
...but that didn't seem to follow any existing pattern, so I didn't go down that route.
If …
=> Fix `PGHISTORY_DEFAULT_TRACKERS` setting

pghistory/migrations/0004_auto_20220906_1625.py
Ran into trouble with our tests, which use an in-memory SQLite database. The solution proposed in #75 fixes this and there doesn't seem to be any issues otherwise. Looks like a PR for it just hasn't been made yet but this should do it.
=> (#75) Don't register trigger on non-Postgres databases

pghistory/models.py
Add `null=True` to both fields of `MiddlewareEvents` model to display all events in the admin.
Closes: https://github.com/Opus10/django-pghistory/issues/129
Type: bug
=> MiddlewareEvents model should allow nullable context

pghistory/middleware.py, pghistory/models.py, pghistory/tests/test_middleware.py
If a tracked model has a custom private key field, which has a different database representation to the instance value, the queryset for `pghistory.models.Event` fails.
Closes: https://github.com/Opus10/django-pghistory/issues/126
Additionally, this fixes middleware to store prepared user PK value in the context.
Type: bug
=> Fix events queryset failing for custom model PKs

pghistory/middleware.py
Hello! We have a project where we use ASGI instead of WSGI to use websocket connections. We just use a custom middleware there, but this might be a useful feature for other people. Let me know what you think.
=> Add ASGI support

pghistory/core.py
When I upgraded pghistory, PyCharm showed me a type error that None is not expected, when it  actually is one of the allowed types. I can surpress this inspection for the entire class, but that is overkill. A correct type hint would be preferable, since None is a valid value and necessary for M2M table add/remove tracking.
=> Correct type hint of def track(obj_field=)

docs/context.md, pghistory/middleware.py
`pghistory.middleware.HistoryMiddleware` has been updates so that it's easier to extend. To add more tracked context, override `get_context` on the middleware object. An example was added to the docs for tracking user IP addresses
=> Make context middleware extensible

docs/event_models.md, docs/event_tracking.md, docs/module.md, docs/settings.md, mkdocs.yml
Some settings, such as `PGHISTORY_DEFAULT_TRACKERS`, were not documented. This PR also cleans up the configuration section
=> Clean up configuration section of docs, ensure all settings are documented

pghistory/config.py, pghistory/constants.py, pghistory/core.py
Some of the type hints for core functions were not correct, especially those that accept/return model types or sentinel values. Although there is some work to go for full type safety with pghistory, this should alleviate many common issues when using the core interface
=> More accurate type hints

docs/context.md
The context tracking guide's example on tracking management commands ignores `migrate`. Recent changes in Pghistory's context tracking add `%s` in the adjusted SQL. If any custom SQL has `%....s` in it without accompanying arguments, this creates a SQL execution error once the SQL is modified.
I made an issue to track this at https://github.com/Opus10/django-pghistory/issues/149
For now, I've updated the doc examples to not track `migrate` whenever tracking management commands. This resolves https://github.com/Opus10/django-pghistory/issues/109
=> Adjust guide on tracking management commands

pghistory/core.py, pghistory/tests/test_core.py, pghistory/tests/test_models.py
`pghistory.create_event` now handles manual creation of events for trackers with denormalized or no context fields. Resolves #115
=> Ensure `pghistory.create_event` is compatible with denormalized context

pghistory/runtime.py
Resolves #117 
It's still unclear what situations result in a `None` execute result. For now doing the obvious fix. Can later add an appropriate failing test when reproduced
=> Check that execute result is not `None` in psycopg3 when using context tracking

pghistory/tests/test_models.py, pghistory/trigger.py
Ran into an issue where pghistory was attempting to copy over the value from a GeneratedField into the corresponding GeneratedField on the Event model, which caused an error since you can't set the value on a GeneratedField. GeneratedFields in general should probably just be ignored by the trigger. I'm aware this may not be implemented too well, let me know if there's anything you'd like me to change or redo.
Thank you!
=> Ignore GeneratedField in trigger function

pghistory/admin/core.py
Instead of overriding the extra_context, update it.
Closes #191
=> Allow passing extra context to the admin template.

docs/performance.md
"...inserted or update." → "...inserted or updated."
=> Fix typo in docs.

pghistory/core.py
ProxyField accepts Field instance, not Field class
ref: https://django-pghistory.readthedocs.io/en/3.7.0/aggregating_events/#querying-context-as-structured-fields
=> Accept Field instance in ProxyField
