Makefile
devops.py
docs/conf.py
pghistory/__init__.py
pghistory/version.py
poetry.lock
pyproject.toml
temple.yaml
tox.ini

Updated with latest Django template, fixing doc builds

---

.circleci/config.yml
Makefile
footing.yaml
pyproject.toml
tox.ini

Test against Django 4.1 and other CI improvements

---

pghistory/tracking.py
poetry.lock

Add JSONEncoder extension to handle types like uuid in metadata

---

pghistory/trigger.py

Format trigger SQL for better compatibility with ``django-pgtrigger``>=4.5

---

pghistory/middleware.py

Use ``settings.PGHISTORY_MIDDLEWARE_METHODS`` to configure which methods
are tracked in the middleware. Defaults to ``("GET", "POST", "PUT", "PATCH", "DELETE")``.
Type: feature

Configure middleware tracked methods

---

pghistory/middleware.py

Do additional safety checks in middleware

---

pghistory/middleware.py

Reference PK of user instead of ID in middleware for DRF-based flows

---

pghistory/migrations/0004_auto_20220906_1625.py
pghistory/models.py

Ensure installation of pghistory context function is installed across multiple databases

---

.circleci/config.yml
.gitignore
CONTRIBUTING.rst
Makefile
environment.yml
footing.yaml
poetry.lock

Update with the latest Django template

---

docs/event_models.rst

In the code and the rest of the docs PGHISTORY_OBJ_FIELD is used.

Correct settings name

---

.gitignore
footing.yaml

Fix ``make lint`` command with new .gitignore changes

---

docs/upgrading.md

Add upgrading notes around the default related name changing.

---

.readthedocs.yml
footing.yaml

PDFs and other offline formats are now created with ReadTheDocs.
Resolves #70

Support offline doc formats

---

docs/event_tracking.md
docs/faq.md

Add section to FAQ on backfilling data

---

pghistory/core.py

Fix minor docstring issue in `pghistory.create_event_model`

---

docs/faq.md

The FAQ section has links to the Q/A discussions in the django-pghistory repo. Also has instructions for opening a new question

Note the Q/A discussions in the FAQ

---

pghistory/models.py

On large datasets `LAG` window function will massively hit the performance.
To improve it, we should benefit from a simple sub-SELECT. The difference in speed is **enormous**!
Tested on the table with ~1 million rows:
- with `LAG`: ~ 40s
- with subquery: 448ms

Optimise CTE query to use subquery instead of window function

---

pghistory/admin/core.py

When we select a record to display in the all events admin, we can optimise the query not to `UNION` other event tables but stick to the original table only.

Optimise query in the events admin detail page

---

pghistory/core.py

fix: use model class from deconstruct to create history model

---

docs/event_models.md
docs/troubleshooting.md

Addresses #218 by adding a troubleshooting section for migrating to denormalized context

Add docs for how to migrate to denormalized context

---

CHANGELOG.md
pghistory/models.py
pyproject.toml

enclosed event table with double quotes
